-- ================================================================
-- DeepDive Workshop OCI 2026
-- SQL Tools Script: schema ORACLELABS + ADMIN compatibility
-- Execute as ADMIN in Database Actions -> SQL
-- ================================================================
SET SERVEROUTPUT ON;

-- 0) Create ORACLELABS user (idempotent)
DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM dba_users WHERE username = 'ORACLELABS';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ORACLELABS IDENTIFIED BY "Welcome123456$"';
    EXECUTE IMMEDIATE 'ALTER USER ORACLELABS QUOTA UNLIMITED ON DATA';
  END IF;
END;
/

-- 1) Base grants
BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ORACLELABS';
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ORACLELABS';
  EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ORACLELABS';
  EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ORACLELABS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1927 THEN
      RAISE;
    END IF;
END;
/

-- 2) Enable DBMS_CLOUD for ORACLELABS (if supported)
-- Note: ENABLE_SCHEMA procedure may not be available in all versions/configurations
-- BEGIN
--   DBMS_CLOUD_ADMIN.ENABLE_SCHEMA(schema_name => 'ORACLELABS');
-- EXCEPTION
--   WHEN OTHERS THEN
--     NULL;
-- END;
-- /

BEGIN
  EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_CLOUD TO ORACLELABS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

-- 3) Create table in ORACLELABS
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ORACLELABS.COBRANZA_MOROSIDAD(
    ID_CASO                    VARCHAR2(64)   NOT NULL,
    CLIENTE_SINTETICO          VARCHAR2(64),
    CUENTA_ID                  VARCHAR2(64),
    SEGMENTO_RIESGO            VARCHAR2(64),
    PRODUCTO_CREDITICIO        VARCHAR2(64),
    SALDO_PENDIENTE_PEN        NUMBER(14,2),
    DIAS_MORA                  NUMBER(4),
    FECHA_VENCIMIENTO          DATE,
    ESTADO_COBRANZA            VARCHAR2(64),
    ULTIMA_GESTION             VARCHAR2(64),
    DOCUMENTO_CLIENTE          VARCHAR2(64),
    NOMBRE_COMPLETO            VARCHAR2(128),
    TELEFONO                   VARCHAR2(32),
    EMAIL                      VARCHAR2(128),
    DIRECCION                  VARCHAR2(256),
    FECHA_ORIGEN_DEUDA         DATE,
    MONTO_ORIGINAL             NUMBER(14,2),
    INTERES_MORATORIO          NUMBER(14,2),
    GASTOS_COBRANZA            NUMBER(14,2),
    MONTO_TOTAL_EXIGIBLE       NUMBER(14,2),
    CUOTAS_PENDIENTES          NUMBER(4),
    CUOTA_MENSUAL              NUMBER(14,2),
    FECHA_PROXIMA_CUOTA        DATE,
    FECHA_ULTIMO_PAGO          DATE,
    MONTO_ULTIMO_PAGO          NUMBER(14,2),
    MONTO_PAGADO_ACUMULADO     NUMBER(14,2),
   CANAL_PREFERIDO_CONTACTO   VARCHAR2(64),
    NUMERO_INTENTOS_CONTACTO   NUMBER(3),
    FECHA_ULTIMO_CONTACTO      DATE,
    RESULTADO_ULTIMO_CONTACTO  VARCHAR2(128),
    PROMESA_PAGO_FECHA         DATE,
    PROMESA_PAGO_MONTO         NUMBER(14,2),
    PROMESA_PAGO_CUMPLIDA      VARCHAR2(16),
    GESTOR_COBRANZA            VARCHAR2(64),
    AGENCIA_O_CARTERA          VARCHAR2(64),
    PRIORIDAD_GESTION          VARCHAR2(32),
    ETAPA_COBRANZA             VARCHAR2(32),
    ACUERDO_REFINANCIACION     VARCHAR2(16),
    FECHA_REFINANCIACION       DATE,
    SALDO_REFINANCIADO         NUMBER(14,2),
    RIESGO_INCUMPLIMIENTO      NUMBER(4,2),
    SCORE_COBRANZA             NUMBER(4),
    FECHA_ACTUALIZACION        DATE,
    USUARIO_ACTUALIZACION      VARCHAR2(64),
    DEPARTAMENTO               VARCHAR2(64),
    PROVINCIA                  VARCHAR2(64),
    DISTRITO                   VARCHAR2(64),
    CONSTRAINT PK_COBRANZA_MOROSIDAD
        PRIMARY KEY (ID_CASO)
   )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ORACLELABS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE COBRANZA_MOROSIDAD';

  
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ADMIN';
EXCEPTION
  WHEN OTHERS THEN
    EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ADMIN';
    RAISE;
END;
/
COMMIT;


-- 5) Refresh ADMIN table from ORACLELABS
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADMIN.COBRANZA_MOROSIDAD PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE ADMIN.COBRANZA_MOROSIDAD AS
SELECT *
FROM ORACLELABS.COBRANZA_MOROSIDAD;


COMMIT;

-- 6) Enable ORDS REST for ORACLELABS
BEGIN
  ORDS.ENABLE_SCHEMA(
    p_enabled             => TRUE,
    p_schema              => 'ORACLELABS',
    p_url_mapping_type    => 'BASE_PATH',
    p_url_mapping_pattern => 'oraclelabs',
    p_auto_rest_auth      => FALSE
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'ORACLELABS',
    p_object         => 'COBRANZA_MOROSIDAD',
    p_object_type    => 'TABLE',
    p_object_alias   => 'COBRANZA_MOROSIDAD',
    p_auto_rest_auth => FALSE
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
COMMIT;

-- 7) Quick validations
SELECT username, account_status
FROM dba_users
WHERE username = 'ORACLELABS';

SELECT COUNT(*) AS total_oraclelabs
FROM ORACLELABS.COBRANZA_MOROSIDAD;

SELECT COUNT(*) AS total_admin
FROM ADMIN.COBRANZA_MOROSIDAD;

DROP TABLE ADMIN.COBRANZA_MOROSIDAD;


-- 8) Print REST URLs
DECLARE
  l_db_name VARCHAR2(128);
BEGIN
  SELECT LOWER(name) INTO l_db_name FROM v$database;

  DBMS_OUTPUT.PUT_LINE('--- ORDS REST ---');
  DBMS_OUTPUT.PUT_LINE('Base schema URL (estimated):');
  DBMS_OUTPUT.PUT_LINE('https://' || l_db_name || '.adb.us-chicago-1.oraclecloudapps.com/ords/oraclelabs/');
  DBMS_OUTPUT.PUT_LINE('Table resource URL:');
  DBMS_OUTPUT.PUT_LINE('https://' || l_db_name || '.adb.us-chicago-1.oraclecloudapps.com/ords/oraclelabs/COBRANZA_MOROSIDAD/');
  DBMS_OUTPUT.PUT_LINE('If URL does not respond, take Database Actions host and append /ords/oraclelabs/');
END;
/

-- AIDP schema hint
-- Preferred schema in external catalog: ORACLELABS
